### PR TITLE
Worker

### PR DESCRIPTION
**Pull request by julesyoungberg**
Managing the workers from the main thread turned out to come with some extra obstacles so I switched to using web workers. This meant rewriting some of the data flow and renaming channels. The data flow works here, but the worker's `loadSound` file seems to be failing. I think because of the unique context (web worker) we may have to decode the files ourselves. I probably won't have time to continue with that until after the proposal though so thought I'd open this, get some eyes on it, and then hopefully merge sooner than later. 

In the meantime, for UI development, we can fill the database with dummy data. This could be pretty easily done as a client side script utilizing the `insert_sound` channel.

### CODE REVIEW

**Review by woofers — APPROVED** [review]

**Comment by julesyoungberg** [comment]
It's progress even if it doesn't work

**Comment by woofers** [comment]
> It's progress even if it doesn't work

@julesyoungberg  Definitely good progress.  Nice work.

I had a quick look.  I think the issue has to do the AudioContext API which can't be created in the Worker threads since it does not have access to the `window`.  As a result we can't decode the audio.  I tried creating the context in the IPC and passing it to the worker, but I think it had issues with being used by multiple threads.

I think we may want to look at the AudioWorklet: https://developers.google.com/web/updates/2017/12/audio-worklet

**Comment by julesyoungberg** [comment]
Shit, yeah we should switch to that. Nice find!

**Comment by julesyoungberg** [comment]
@woofers after some more research I don't think AudioWorklet is what we want. Those are for real-time processing but we are doing it offline so we don't actually need AudioContext. However, since imports from workers are resolved for the browser (even though electron has full node integration in web workers), we are getting undefined errors. I've got around `audio-loader`, now just need to get `audio-decode` working.

**Pull request merged**
